version: '3.8'
name: real-time-notify-service
services:
  mysql:
    container_name: real-time-notify-service-mysql-core
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=real-time-notify-service-bd
      - MYSQL_ROOT_PASSWORD=123456789*
    ports:
      - '3306:3306'

  prometheus:
    image: prom/prometheus
    container_name: real-time-notify-service-prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9090:9090'
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    network_mode: "host"

  grafana:
    image: grafana/grafana
    container_name: real-time-notify-service-grafana
    ports:
      - '3000:3000'
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    network_mode: "host"

  redis:
    container_name: real-time-notify-service-redis
    image: redis:latest
    ports:
      - '6379:6379'
    environment:
      - REDIS_PORT=6379
    depends_on:
       - mysql

  zookeeper:
    container_name: real-time-notify-service-zookeeper
    image: confluentinc/cp-zookeeper
    ports:
      - '2182:2181'
    environment:
      - ZOOKEEPER_CLIENT_PORT=2181
    depends_on:
      - mysql

  kafka-0:
    container_name: real-time-notify-service-kafka-0
    image: confluentinc/cp-kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka-0:29094,PLAINTEXT_HOST://localhost:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:29094,PLAINTEXT_HOST://0.0.0.0:9092
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
    depends_on:
      - mysql
      - zookeeper

volumes:
  prom_data: